### ISSUE TITLE
Messaging in github.

### ISSUE THREAD

**Issue by Sima214** [Sima214/genume#1]
@drazioti is there any way we could merge our work?
I didn't really want to involved with the gui portion, so I made an interface for automatically collecting information from scripts. No static imports/executions, everything is done dynamically and gets collected in a dict-like data structure.

**Comment by drazioti** [comment]
Sure. Fork my branch and apply what you have in mind.

**Comment by Sima214** [comment]
I merged our branches into a new branch semi-successfully~
